/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package memotest;
import memotest.Tablero;
import javax.swing.*;
import java.io.*;
/**
 *
 * @author juanz
 */
public class JfJuegoMemoria extends javax.swing.JFrame {
    private Tablero tablero;
    private Tablero4x4 tablero4x4;
    private Tablero6x6 tablero6x6;
    private Tablero8x8 tablero8x8;

     /**
     * Creates new form JfJuegoMemoria
     */
    public JfJuegoMemoria() {
        initComponents();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        JPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BT4x4 = new javax.swing.JButton();
        BT6x6 = new javax.swing.JButton();
        BT8x8 = new javax.swing.JButton();
        BTsalir = new javax.swing.JButton();
        BTguardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BTcargar = new javax.swing.JButton();
        lblMovimientos = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Niveles:");

        BT4x4.setBackground(new java.awt.Color(102, 0, 204));
        BT4x4.setForeground(new java.awt.Color(255, 255, 255));
        BT4x4.setText("4x4");
        BT4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT4x4ActionPerformed(evt);
            }
        });

        BT6x6.setBackground(new java.awt.Color(102, 0, 204));
        BT6x6.setForeground(new java.awt.Color(255, 255, 255));
        BT6x6.setText("6x6");
        BT6x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT6x6ActionPerformed(evt);
            }
        });

        BT8x8.setBackground(new java.awt.Color(102, 0, 204));
        BT8x8.setForeground(new java.awt.Color(255, 255, 255));
        BT8x8.setText("8x8");
        BT8x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT8x8ActionPerformed(evt);
            }
        });

        BTsalir.setBackground(new java.awt.Color(102, 0, 204));
        BTsalir.setForeground(new java.awt.Color(255, 255, 255));
        BTsalir.setText("Salir");
        BTsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsalirActionPerformed(evt);
            }
        });

        BTguardar.setBackground(new java.awt.Color(102, 0, 204));
        BTguardar.setForeground(new java.awt.Color(255, 255, 255));
        BTguardar.setText("Guardar");
        BTguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTguardarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 204));
        jLabel2.setText("JUEGO DE MEMORIA");

        BTcargar.setBackground(new java.awt.Color(102, 0, 204));
        BTcargar.setForeground(new java.awt.Color(255, 255, 255));
        BTcargar.setText("Cargar");
        BTcargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcargarActionPerformed(evt);
            }
        });

        lblMovimientos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movimientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        lblPuntos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Puntos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(BTguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTcargar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(BT6x6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BT8x8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                        .addComponent(BTsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMovimientos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuntos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 352, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT6x6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT8x8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTcargar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT6x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT6x6ActionPerformed
        // TODO add your handling code here:
        try {
            mostrarOpciones(new Tablero6x6(JPanel1, lblPuntos, lblMovimientos));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar iniciar el juego 6x6: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BT6x6ActionPerformed

    private void BTsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsalirActionPerformed
        // TODO add your handling code here:  
        int responde = JOptionPane.showConfirmDialog(null, "¿Desea guardar antes de salir?", "Salir", JOptionPane.YES_NO_CANCEL_OPTION);
        if (responde == JOptionPane.YES_OPTION) {
            BTguardarActionPerformed(evt);
            System.exit(0);
        } else if (responde == JOptionPane.NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_BTsalirActionPerformed

    private void BT4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT4x4ActionPerformed
        // TODO add your handling code here:
         try {
            mostrarOpciones(new Tablero4x4(JPanel1, lblPuntos, lblMovimientos));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar iniciar el juego 4x4: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BT4x4ActionPerformed

    private void BT8x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT8x8ActionPerformed
        // TODO add your handling code here:
        try {
            mostrarOpciones(new Tablero8x8(JPanel1, lblPuntos, lblMovimientos));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar iniciar el juego 8x8: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BT8x8ActionPerformed

    private void BTguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTguardarActionPerformed
        // TODO add your handling code here:
          try {
            File fichero = new File("C:\\Temp\\estadísticas.txt");
            if (!fichero.exists()) {
                fichero.createNewFile();
            }

            BufferedWriter bw = new BufferedWriter(new FileWriter(fichero, false));
            bw.write(tablero.puntos + "," + tablero.movimientos);
            bw.close();

            JOptionPane.showMessageDialog(this, "Estadísticas guardadas correctamente.");
        } catch (IOException ioe) {
            ioe.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al guardar las estadísticas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTguardarActionPerformed

    private void BTcargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcargarActionPerformed
        // TODO add your handling code here:
        try {
            File fichero = new File("C:\\Temp\\estadísticas.txt");
            if (fichero.exists()) {
                BufferedReader br = new BufferedReader(new FileReader(fichero));
                String linea = br.readLine();
                if (linea != null) {
                    String[] datos = linea.split(",");
                    tablero.puntos = Integer.parseInt(datos[0]);
                    tablero.movimientos = Integer.parseInt(datos[1]);
                    tablero.actualizarPuntosYMovimientos();
                }
                br.close();
                JOptionPane.showMessageDialog(this, "Estadísticas cargadas correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontraron estadísticas previas para cargar.", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ioe) {
            ioe.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al leer las estadísticas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTcargarActionPerformed

    private void mostrarOpciones(Tablero nuevoTablero) {
        String[] opciones = {"Continuar", "Nuevo"};
        int respuesta = JOptionPane.showOptionDialog(null, "Seleccione una opción", "Opciones Tablero",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[0]);

        if (respuesta == 0) { // Continuar
            BTcargarActionPerformed(null);
        } else if (respuesta == 1) { // Nuevo
            tablero = nuevoTablero;
            tablero.iniciarTablero();
        }
    }
    
    private void reiniciarTablero(Tablero nuevoTablero) {
        JPanel1.removeAll();
        tablero = nuevoTablero;
        tablero.iniciarTablero();
        JPanel1.revalidate();
        JPanel1.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfJuegoMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfJuegoMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfJuegoMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfJuegoMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfJuegoMemoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT4x4;
    private javax.swing.JButton BT6x6;
    private javax.swing.JButton BT8x8;
    private javax.swing.JButton BTcargar;
    private javax.swing.JButton BTguardar;
    private javax.swing.JButton BTsalir;
    private javax.swing.JPanel JPanel1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblMovimientos;
    private javax.swing.JLabel lblPuntos;
    // End of variables declaration//GEN-END:variables

}
